services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: donate_raid
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: unless-stopped

  backend:
    build: ./backend
    env_file: .env
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    environment:
      - BOT_MODE=false
    restart: unless-stopped
    volumes:
      - ./backend/logs:/app/logs

  bot:
    build: ./backend
    command: ./start.sh
    env_file: .env
    depends_on:
      - backend
    environment:
      - BOT_MODE=true
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata_prod: