services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: donate_raid
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5435:5432"  # Только localhost - БД не должна быть доступна извне
    restart: unless-stopped

  backend:
    build: ./backend
    env_file: .env
    ports:
      - "8001:8000"  # Убираем 127.0.0.1, чтобы было доступно извне
    depends_on:
      - postgres
    environment:
      - BOT_MODE=false
    restart: unless-stopped
    volumes:
      - ./backend/logs:/app/logs

  bot:
    build: ./backend
    command: ./start.sh
    env_file: .env
    depends_on:
      - backend
    environment:
      - BOT_MODE=true
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}  # Передаем из .env
    ports:
      - "3001:3000"  # Убираем 127.0.0.1, чтобы было доступно извне
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  pgdata_prod: