services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: donate_raid
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"  # Только localhost - БД не должна быть доступна извне
    restart: unless-stopped
    networks:
      - donateraid

  backend:
    build: ./backend
    env_file: .env
    ports:
      - "127.0.0.1:8001:8000"  # Только localhost, через nginx
    depends_on:
      - postgres
    environment:
      - BOT_MODE=false
    restart: unless-stopped
    volumes:
      - ./backend/logs:/app/logs
      - ./uploads:/app/uploads
    networks:
      - donateraid

  bot:
    build: ./backend
    command: ./start.sh
    env_file: .env
    depends_on:
      - backend
    environment:
      - BOT_MODE=true
    restart: unless-stopped
    networks:
      - donateraid

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - NEXT_PUBLIC_API_URL=https://donateraid.ru/api
        - NEXT_PUBLIC_WS_URL=wss://donateraid.ru
    ports:
      - "127.0.0.1:3001:3000"  # Только localhost, через nginx
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - donateraid

networks:
  donateraid:
    driver: bridge

volumes:
  pgdata_prod: