"""add guest_id to support_messages

Revision ID: 1c1a2c749a29
Revises: 89223fff209d
Create Date: 2025-06-04 15:00:19.131235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c1a2c749a29'
down_revision: Union[str, None] = '89223fff209d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_messages', sa.Column('guest_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_messages', 'guest_id')
    # ### end Alembic commands ###
