"""add referral system and game improvements

Revision ID: 33e7f99fa1c7
Revises: 7e3fb385c3eb
Create Date: 2025-06-12 13:59:11.549283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33e7f99fa1c7'
down_revision: Union[str, None] = '7e3fb385c3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_tags_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_article_tags_table_id'), 'article_tags_table', ['id'], unique=False)
    op.create_table('payment_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_terms_id'), 'payment_terms', ['id'], unique=False)
    op.create_table('article_tags',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['article_tags_table.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'tag_id')
    )
    op.create_table('game_faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_faqs_id'), 'game_faqs', ['id'], unique=False)
    op.create_table('game_instructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_instructions_id'), 'game_instructions', ['id'], unique=False)
    op.create_table('referral_earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_earnings_id'), 'referral_earnings', ['id'], unique=False)
    op.create_index(op.f('ix_referral_earnings_order_id'), 'referral_earnings', ['order_id'], unique=False)
    op.create_index(op.f('ix_referral_earnings_referrer_id'), 'referral_earnings', ['referrer_id'], unique=False)
    op.add_column('articles', sa.Column('excerpt', sa.String(length=500), nullable=True))
    op.add_column('articles', sa.Column('featured_image_url', sa.String(length=500), nullable=True))
    op.add_column('articles', sa.Column('featured_image_alt', sa.String(length=255), nullable=True))
    op.add_column('articles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('articles', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('articles_game_id_fkey'), 'articles', type_='foreignkey')
    op.drop_column('articles', 'author_name')
    op.drop_column('articles', 'category')
    op.drop_column('articles', 'game_id')
    op.add_column('games', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('subcategory_description', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('logo_url', sa.String(length=255), nullable=True))
    op.add_column('games', sa.Column('faq_content', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.alter_column('games', 'banner_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('users', sa.Column('referral_code', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('referred_by_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('referral_earnings', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('users', sa.Column('total_referrals', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_foreign_key(None, 'users', 'users', ['referred_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_column('users', 'total_referrals')
    op.drop_column('users', 'referral_earnings')
    op.drop_column('users', 'referred_by_id')
    op.drop_column('users', 'referral_code')
    op.alter_column('games', 'banner_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('games', 'enabled')
    op.drop_column('games', 'faq_content')
    op.drop_column('games', 'logo_url')
    op.drop_column('games', 'subcategory_description')
    op.drop_column('games', 'description')
    op.add_column('articles', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('category', postgresql.ENUM('news', 'guide', 'promo', 'review', 'pc', 'mobile', name='articlecategory'), autoincrement=False, nullable=False))
    op.add_column('articles', sa.Column('author_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('articles_game_id_fkey'), 'articles', 'games', ['game_id'], ['id'])
    op.drop_column('articles', 'published_at')
    op.drop_column('articles', 'updated_at')
    op.drop_column('articles', 'featured_image_alt')
    op.drop_column('articles', 'featured_image_url')
    op.drop_column('articles', 'excerpt')
    op.drop_index(op.f('ix_referral_earnings_referrer_id'), table_name='referral_earnings')
    op.drop_index(op.f('ix_referral_earnings_order_id'), table_name='referral_earnings')
    op.drop_index(op.f('ix_referral_earnings_id'), table_name='referral_earnings')
    op.drop_table('referral_earnings')
    op.drop_index(op.f('ix_game_instructions_id'), table_name='game_instructions')
    op.drop_table('game_instructions')
    op.drop_index(op.f('ix_game_faqs_id'), table_name='game_faqs')
    op.drop_table('game_faqs')
    op.drop_table('article_tags')
    op.drop_index(op.f('ix_payment_terms_id'), table_name='payment_terms')
    op.drop_table('payment_terms')
    op.drop_index(op.f('ix_article_tags_table_id'), table_name='article_tags_table')
    op.drop_table('article_tags_table')
    # ### end Alembic commands ###
