"""add sort_order to Game and Product

Revision ID: 53e210c3db1d
Revises: 511a17723415
Create Date: 2025-05-30 13:25:54.533989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e210c3db1d'
down_revision: Union[str, None] = '511a17723415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('games', sa.Column(
        'sort_order',
        sa.Integer(),
        nullable=False,
        server_default="0"
    ))
    op.add_column('orders', sa.Column(
        'manual_game_name',
        sa.String(length=255),
        nullable=True
    ))
    op.add_column('products', sa.Column(
        'sort_order',
        sa.Integer(),
        nullable=False,
        server_default="0"
    ))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sort_order')
    op.drop_column('orders', 'manual_game_name')
    op.drop_column('games', 'sort_order')
    # ### end Alembic commands ###
