"""add missing fields to article model

Revision ID: 554051946785
Revises: 347db8c9214b
Create Date: 2025-06-14 12:00:33.894324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '554051946785'
down_revision: Union[str, None] = '347db8c9214b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('articles', sa.Column('game_id', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('author_name', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'articles', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'author_name')
    op.drop_column('articles', 'game_id')
    op.drop_column('articles', 'category')
    # ### end Alembic commands ###
