"""add is_category field to article tags

Revision ID: f3888e5c9b55
Revises: 554051946785
Create Date: 2025-06-15 14:33:12.033017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3888e5c9b55'
down_revision: Union[str, None] = '554051946785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_tags_table', sa.Column('is_category', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_tags_table', 'is_category')
    # ### end Alembic commands ###
